In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/nafda1801/british-airways-internship/British Airways Summer Schedule Dataset - Forage Data Science Task 1.xlsx

In [2]:
df = pd.read_excel('/kaggle/input/datasets/nafda1801/british-airways-internship/British Airways Summer Schedule Dataset - Forage Data Science Task 1.xlsx')

In [3]:
df.head()

,FLIGHT_DATE,FLIGHT_TIME,TIME_OF_DAY,AIRLINE_CD,FLIGHT_NO,DEPARTURE_STATION_CD,ARRIVAL_STATION_CD,ARRIVAL_COUNTRY,ARRIVAL_REGION,HAUL,AIRCRAFT_TYPE,FIRST_CLASS_SEATS,BUSINESS_CLASS_SEATS,ECONOMY_SEATS,TIER1_ELIGIBLE_PAX,TIER2_ELIGIBLE_PAX,TIER3_ELIGIBLE_PAX
0,2025-09-02,14:19:00,Afternoon,BA,BA5211,LHR,LAX,USA,North America,LONG,B777,8,49,178,0,10,38
1,2025-06-10,06:42:00,Morning,BA,BA7282,LHR,LAX,USA,North America,LONG,B777,8,49,178,0,7,28
2,2025-10-27,15:33:00,Afternoon,BA,BA1896,LHR,FRA,Germany,Europe,SHORT,A320,0,17,163,0,11,40
3,2025-06-15,18:29:00,Evening,BA,BA5497,LHR,IST,Turkey,Europe,SHORT,A320,0,8,172,0,16,54
4,2025-08-25,20:35:00,Evening,BA,BA1493,LHR,FRA,Germany,Europe,SHORT,A320,0,13,167,0,6,27

In [4]:
 df['FLIGHT_TIME'].dtype

dtype('O')

In [5]:
df['seconds_since_midnight'] = df['FLIGHT_TIME'].apply(
    lambda t: (t.hour * 3600) + (t.minute * 60) + t.second if t is not None else None
)

In [6]:
df['Total_Passengers']=df['FIRST_CLASS_SEATS']+ df['BUSINESS_CLASS_SEATS'] + df['ECONOMY_SEATS']

In [7]:
df.head()

,FLIGHT_DATE,FLIGHT_TIME,TIME_OF_DAY,AIRLINE_CD,FLIGHT_NO,DEPARTURE_STATION_CD,ARRIVAL_STATION_CD,ARRIVAL_COUNTRY,ARRIVAL_REGION,HAUL,AIRCRAFT_TYPE,FIRST_CLASS_SEATS,BUSINESS_CLASS_SEATS,ECONOMY_SEATS,TIER1_ELIGIBLE_PAX,TIER2_ELIGIBLE_PAX,TIER3_ELIGIBLE_PAX,seconds_since_midnight,Total_Passengers
0,2025-09-02,14:19:00,Afternoon,BA,BA5211,LHR,LAX,USA,North America,LONG,B777,8,49,178,0,10,38,51540,235
1,2025-06-10,06:42:00,Morning,BA,BA7282,LHR,LAX,USA,North America,LONG,B777,8,49,178,0,7,28,24120,235
2,2025-10-27,15:33:00,Afternoon,BA,BA1896,LHR,FRA,Germany,Europe,SHORT,A320,0,17,163,0,11,40,55980,180
3,2025-06-15,18:29:00,Evening,BA,BA5497,LHR,IST,Turkey,Europe,SHORT,A320,0,8,172,0,16,54,66540,180
4,2025-08-25,20:35:00,Evening,BA,BA1493,LHR,FRA,Germany,Europe,SHORT,A320,0,13,167,0,6,27,74100,180

In [8]:
df['tier1_pct']=df['TIER1_ELIGIBLE_PAX']*100/df['Total_Passengers']
df['tier2_pct']=df['TIER2_ELIGIBLE_PAX']*100/df['Total_Passengers']
df['tier3_pct']=df['TIER3_ELIGIBLE_PAX']*100/df['Total_Passengers']
df.head()

,FLIGHT_DATE,FLIGHT_TIME,TIME_OF_DAY,AIRLINE_CD,FLIGHT_NO,DEPARTURE_STATION_CD,ARRIVAL_STATION_CD,ARRIVAL_COUNTRY,ARRIVAL_REGION,HAUL,...,BUSINESS_CLASS_SEATS,ECONOMY_SEATS,TIER1_ELIGIBLE_PAX,TIER2_ELIGIBLE_PAX,TIER3_ELIGIBLE_PAX,seconds_since_midnight,Total_Passengers,tier1_pct,tier2_pct,tier3_pct
0,2025-09-02,14:19:00,Afternoon,BA,BA5211,LHR,LAX,USA,North America,LONG,...,49,178,0,10,38,51540,235,0.0,4.255319,16.170213
1,2025-06-10,06:42:00,Morning,BA,BA7282,LHR,LAX,USA,North America,LONG,...,49,178,0,7,28,24120,235,0.0,2.978723,11.914894
2,2025-10-27,15:33:00,Afternoon,BA,BA1896,LHR,FRA,Germany,Europe,SHORT,...,17,163,0,11,40,55980,180,0.0,6.111111,22.222222
3,2025-06-15,18:29:00,Evening,BA,BA5497,LHR,IST,Turkey,Europe,SHORT,...,8,172,0,16,54,66540,180,0.0,8.888889,30.000000
4,2025-08-25,20:35:00,Evening,BA,BA1493,LHR,FRA,Germany,Europe,SHORT,...,13,167,0,6,27,74100,180,0.0,3.333333,15.000000

In [9]:
df['Business_ratio']=df['BUSINESS_CLASS_SEATS']/df['Total_Passengers']
df['First_ratio'] = df['FIRST_CLASS_SEATS']/df['Total_Passengers']
df['Economy_ratio'] = df['ECONOMY_SEATS']/df['Total_Passengers']

In [10]:
df.head()

,FLIGHT_DATE,FLIGHT_TIME,TIME_OF_DAY,AIRLINE_CD,FLIGHT_NO,DEPARTURE_STATION_CD,ARRIVAL_STATION_CD,ARRIVAL_COUNTRY,ARRIVAL_REGION,HAUL,...,TIER2_ELIGIBLE_PAX,TIER3_ELIGIBLE_PAX,seconds_since_midnight,Total_Passengers,tier1_pct,tier2_pct,tier3_pct,Business_ratio,First_ratio,Economy_ratio
0,2025-09-02,14:19:00,Afternoon,BA,BA5211,LHR,LAX,USA,North America,LONG,...,10,38,51540,235,0.0,4.255319,16.170213,0.208511,0.034043,0.757447
1,2025-06-10,06:42:00,Morning,BA,BA7282,LHR,LAX,USA,North America,LONG,...,7,28,24120,235,0.0,2.978723,11.914894,0.208511,0.034043,0.757447
2,2025-10-27,15:33:00,Afternoon,BA,BA1896,LHR,FRA,Germany,Europe,SHORT,...,11,40,55980,180,0.0,6.111111,22.222222,0.094444,0.000000,0.905556
3,2025-06-15,18:29:00,Evening,BA,BA5497,LHR,IST,Turkey,Europe,SHORT,...,16,54,66540,180,0.0,8.888889,30.000000,0.044444,0.000000,0.955556
4,2025-08-25,20:35:00,Evening,BA,BA1493,LHR,FRA,Germany,Europe,SHORT,...,6,27,74100,180,0.0,3.333333,15.000000,0.072222,0.000000,0.927778

In [12]:
lookup = (
    df.groupby(
        ["TIME_OF_DAY", "HAUL", "ARRIVAL_REGION"]
    )
    .agg(
        flights=("FLIGHT_NO", "count"),
        tier1_pct=("tier1_pct", "mean"),
        tier2_pct=("tier2_pct", "mean"),
        tier3_pct=("tier3_pct", "mean")
    )
    .reset_index()
)

lookup

   TIME_OF_DAY   HAUL ARRIVAL_REGION  flights  tier1_pct  tier2_pct  tier3_pct
0    Afternoon   LONG           Asia      152   0.177691   3.045675  11.448006
1    Afternoon   LONG    Middle East      159   0.219675   2.744624  10.536387
2    Afternoon   LONG  North America      628   0.208325   2.959584  11.267637
3    Afternoon  SHORT         Europe     1366   0.341630   4.313486  16.587360
4      Evening   LONG           Asia      206   0.222118   2.883557  11.063940
5      Evening   LONG    Middle East      201   0.234891   2.779583  10.674780
6      Evening   LONG  North America      783   0.227519   2.881922  11.027967
7      Evening  SHORT         Europe     1783   0.328410   4.451611  16.995700
8    Lunchtime   LONG           Asia       75   0.164850   2.703916  10.644564
9    Lunchtime   LONG    Middle East       79   0.195196   2.915522  11.138069
10   Lunchtime   LONG  North America      281   0.197806   2.931033  11.142503
11   Lunchtime  SHORT         Europe      757   0.394100   4.548657  17.275062
12     Morning   LONG           Asia      246   0.228609   2.775138  10.722595
13     Morning   LONG    Middle East      249   0.207989   2.955042  11.233013
14     Morning   LONG  North America      966   0.223177   2.995854  11.395565
15     Morning  SHORT         Europe     2069   0.339939   4.357983  16.742925

In [13]:
for col in ["TIME_OF_DAY", "HAUL", "ARRIVAL_REGION"]:
    print(f"\n===== {col} =====")
    print(
        df.groupby(col)[
            ["tier1_pct", "tier2_pct", "tier3_pct"]
        ].mean()
    )

===== TIME_OF_DAY =====
             tier1_pct  tier2_pct  tier3_pct
TIME_OF_DAY
Afternoon     0.286088   3.752789  14.381688
Evening       0.288151   3.816507  14.585615
Lunchtime     0.320219   3.943015  15.005466
Morning       0.290920   3.775963  14.471390

===== HAUL =====
       tier1_pct  tier2_pct  tier3_pct
HAUL
LONG    0.216364   2.915885  11.131266
SHORT   0.343747   4.399907  16.850209

===== ARRIVAL_REGION =====
                tier1_pct  tier2_pct  tier3_pct
ARRIVAL_REGION
Asia             0.208198   2.860726  10.979925
Europe           0.343747   4.399907  16.850209
Middle East      0.217080   2.850615  10.898029
North America    0.218265   2.946870  11.230298

In [18]:
summary = (
    df.groupby("ARRIVAL_REGION")[["tier3_pct", "tier2_pct", "tier1_pct"]]
    .mean()
)

summary["tier3_range"] = (
    summary["tier3_pct"].max() -
    summary["tier3_pct"].min()
)
summary["tier2_range"] = (
    summary["tier2_pct"].max() -
    summary["tier2_pct"].min()
)
summary["tier1_range"] = (
    summary["tier1_pct"].max() -
    summary["tier1_pct"].min()
)

summary

,tier3_pct,tier2_pct,tier1_pct,tier3_range,tier2_range,tier1_range
ARRIVAL_REGION,,,,,,
Asia,10.979925,2.860726,0.208198,5.95218,1.549292,0.135549
Europe,16.850209,4.399907,0.343747,5.95218,1.549292,0.135549
Middle East,10.898029,2.850615,0.217080,5.95218,1.549292,0.135549
North America,11.230298,2.946870,0.218265,5.95218,1.549292,0.135549

In [19]:
df.groupby(
    ["HAUL", "TIME_OF_DAY"]
)[["tier1_pct", "tier2_pct", "tier3_pct"]].mean().round(3)

                   tier1_pct  tier2_pct  tier3_pct
HAUL  TIME_OF_DAY
LONG  Afternoon        0.205      2.937     11.173
      Evening          0.228      2.865     10.975
      Lunchtime        0.192      2.889     11.056
      Morning          0.222      2.952     11.255
SHORT Afternoon        0.342      4.313     16.587
      Evening          0.328      4.452     16.996
      Lunchtime        0.394      4.549     17.275
      Morning          0.340      4.358     16.743

In [20]:
weighted_lookup = (
    df.groupby("HAUL")
      .agg(
          total_pax=("Total_Passengers", "sum"),
          tier1_pax=("TIER1_ELIGIBLE_PAX", "sum"),
          tier2_pax=("TIER2_ELIGIBLE_PAX", "sum"),
          tier3_pax=("TIER3_ELIGIBLE_PAX", "sum")
      )
      .reset_index()
)

weighted_lookup["tier1_pct"] = (
    weighted_lookup["tier1_pax"] /
    weighted_lookup["total_pax"] * 100
)

weighted_lookup["tier2_pct"] = (
    weighted_lookup["tier2_pax"] /
    weighted_lookup["total_pax"] * 100
)

weighted_lookup["tier3_pct"] = (
    weighted_lookup["tier3_pax"] /
    weighted_lookup["total_pax"] * 100
)

weighted_lookup

,HAUL,total_pax,tier1_pax,tier2_pax,tier3_pax,tier1_pct,tier2_pct,tier3_pct
0,LONG,1174569,2380,32198,122990,0.202628,2.741261,10.471075
1,SHORT,1075500,3697,47321,181224,0.343747,4.399907,16.850209

In [21]:
weighted_time = (
    df.groupby(["HAUL", "TIME_OF_DAY"])
      .agg(
          total_pax=("Total_Passengers", "sum"),
          tier1_pax=("TIER1_ELIGIBLE_PAX", "sum"),
          tier2_pax=("TIER2_ELIGIBLE_PAX", "sum"),
          tier3_pax=("TIER3_ELIGIBLE_PAX", "sum")
      )
      .reset_index()
)

for tier in [1, 2, 3]:
    weighted_time[f"tier{tier}_pct"] = (
        weighted_time[f"tier{tier}_pax"] /
        weighted_time["total_pax"] * 100
    )

weighted_time

,HAUL,TIME_OF_DAY,total_pax,tier1_pax,tier2_pax,tier3_pax,tier1_pct,tier2_pct,tier3_pct
0,LONG,Afternoon,274736,545,7598,28906,0.198372,2.765564,10.521373
1,LONG,Evening,347168,736,9285,35634,0.212001,2.674498,10.264195
2,LONG,Lunchtime,126102,223,3418,13094,0.176841,2.710504,10.383658
3,LONG,Morning,426563,876,11897,45356,0.205362,2.789037,10.632896
4,SHORT,Afternoon,245880,840,10606,40785,0.341630,4.313486,16.587360
5,SHORT,Evening,320940,1054,14287,54546,0.328410,4.451611,16.995700
6,SHORT,Lunchtime,136260,537,6198,23539,0.394100,4.548657,17.275062
7,SHORT,Morning,372420,1266,16230,62354,0.339939,4.357983,16.742925